name: Linter workflow
on: [push]
jobs:
  ejecutar_linter:
   runs-on: ubuntu-latest
   steps:
    - name: Obtencion del codigo
      uses: actions/checkout@v2
    - name: Ejecutar linter
      uses: github/super-linter@v4
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        LINTER_RULES_PATH: /
        JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
        VALIDATE_JAVASCRIPT_ES: true
  ejecutar_test:
    - name: Obtencion del codigo
      uses: actions/checkout@v2
    - name: Obtencion del codigo
      run: npm install jest && npm test
